Workshop
patrjam/codeceptjs-workshop pull request #1
Opened 2021-05-06 13:17 UTC by knapod01

2021-05-06 13:28 UTC, karelsvoboda91 approved these changes

2021-05-13 07:21 UTC, patrjam requested changes

2021-05-13 07:21 UTC, patrjam commented on tests/login_test.js
> +Scenario('test something', ({ I, LoginPage }) => {
Please, use the right scenario name of what are you testing.

2021-05-13 07:28 UTC, karelsvoboda91 requested changes
Please, use the right scenario name of what are you testing.

2021-05-13 07:42 UTC, karelsvoboda91 approved these changes

2021-08-12 16:09 UTC, merged